// Generated by gencpp from file hw1/GenerateMazeRequest.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GENERATEMAZEREQUEST_H
#define HW1_MESSAGE_GENERATEMAZEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct GenerateMazeRequest_
{
  typedef GenerateMazeRequest_<ContainerAllocator> Type;

  GenerateMazeRequest_()
    : dimension(0)
    , obstacles(0)
    , seed(0)  {
    }
  GenerateMazeRequest_(const ContainerAllocator& _alloc)
    : dimension(0)
    , obstacles(0)
    , seed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _dimension_type;
  _dimension_type dimension;

   typedef uint32_t _obstacles_type;
  _obstacles_type obstacles;

   typedef uint32_t _seed_type;
  _seed_type seed;





  typedef boost::shared_ptr< ::hw1::GenerateMazeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::GenerateMazeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateMazeRequest_

typedef ::hw1::GenerateMazeRequest_<std::allocator<void> > GenerateMazeRequest;

typedef boost::shared_ptr< ::hw1::GenerateMazeRequest > GenerateMazeRequestPtr;
typedef boost::shared_ptr< ::hw1::GenerateMazeRequest const> GenerateMazeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::GenerateMazeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::GenerateMazeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::GenerateMazeRequest_<ContainerAllocator1> & lhs, const ::hw1::GenerateMazeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dimension == rhs.dimension &&
    lhs.obstacles == rhs.obstacles &&
    lhs.seed == rhs.seed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::GenerateMazeRequest_<ContainerAllocator1> & lhs, const ::hw1::GenerateMazeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GenerateMazeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GenerateMazeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GenerateMazeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eac2a3c1504426dbffba8540cb404b80";
  }

  static const char* value(const ::hw1::GenerateMazeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeac2a3c1504426dbULL;
  static const uint64_t static_value2 = 0xffba8540cb404b80ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/GenerateMazeRequest";
  }

  static const char* value(const ::hw1::GenerateMazeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 dimension\n"
"uint32 obstacles\n"
"uint32 seed\n"
;
  }

  static const char* value(const ::hw1::GenerateMazeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dimension);
      stream.next(m.obstacles);
      stream.next(m.seed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateMazeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::GenerateMazeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::GenerateMazeRequest_<ContainerAllocator>& v)
  {
    s << indent << "dimension: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dimension);
    s << indent << "obstacles: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.obstacles);
    s << indent << "seed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_GENERATEMAZEREQUEST_H
