// Generated by gencpp from file hw1/GenerateMaze.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GENERATEMAZE_H
#define HW1_MESSAGE_GENERATEMAZE_H

#include <ros/service_traits.h>


#include <hw1/GenerateMazeRequest.h>
#include <hw1/GenerateMazeResponse.h>


namespace hw1
{

struct GenerateMaze
{

typedef GenerateMazeRequest Request;
typedef GenerateMazeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateMaze
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::GenerateMaze > {
  static const char* value()
  {
    return "91077eae89da535fbefd16adcdc2fbc7";
  }

  static const char* value(const ::hw1::GenerateMaze&) { return value(); }
};

template<>
struct DataType< ::hw1::GenerateMaze > {
  static const char* value()
  {
    return "hw1/GenerateMaze";
  }

  static const char* value(const ::hw1::GenerateMaze&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::GenerateMazeRequest> should match
// service_traits::MD5Sum< ::hw1::GenerateMaze >
template<>
struct MD5Sum< ::hw1::GenerateMazeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GenerateMaze >::value();
  }
  static const char* value(const ::hw1::GenerateMazeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GenerateMazeRequest> should match
// service_traits::DataType< ::hw1::GenerateMaze >
template<>
struct DataType< ::hw1::GenerateMazeRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::GenerateMaze >::value();
  }
  static const char* value(const ::hw1::GenerateMazeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::GenerateMazeResponse> should match
// service_traits::MD5Sum< ::hw1::GenerateMaze >
template<>
struct MD5Sum< ::hw1::GenerateMazeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GenerateMaze >::value();
  }
  static const char* value(const ::hw1::GenerateMazeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GenerateMazeResponse> should match
// service_traits::DataType< ::hw1::GenerateMaze >
template<>
struct DataType< ::hw1::GenerateMazeResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::GenerateMaze >::value();
  }
  static const char* value(const ::hw1::GenerateMazeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_GENERATEMAZE_H
