// Generated by gencpp from file hw1/GenerateMazeResponse.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GENERATEMAZERESPONSE_H
#define HW1_MESSAGE_GENERATEMAZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct GenerateMazeResponse_
{
  typedef GenerateMazeResponse_<ContainerAllocator> Type;

  GenerateMazeResponse_()
    : done(0)  {
    }
  GenerateMazeResponse_(const ContainerAllocator& _alloc)
    : done(0)  {
  (void)_alloc;
    }



   typedef uint32_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::hw1::GenerateMazeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::GenerateMazeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateMazeResponse_

typedef ::hw1::GenerateMazeResponse_<std::allocator<void> > GenerateMazeResponse;

typedef boost::shared_ptr< ::hw1::GenerateMazeResponse > GenerateMazeResponsePtr;
typedef boost::shared_ptr< ::hw1::GenerateMazeResponse const> GenerateMazeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::GenerateMazeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::GenerateMazeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::GenerateMazeResponse_<ContainerAllocator1> & lhs, const ::hw1::GenerateMazeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::GenerateMazeResponse_<ContainerAllocator1> & lhs, const ::hw1::GenerateMazeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GenerateMazeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GenerateMazeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GenerateMazeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b104abac0b485abf5b3ab163fc24088";
  }

  static const char* value(const ::hw1::GenerateMazeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b104abac0b485abULL;
  static const uint64_t static_value2 = 0xf5b3ab163fc24088ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/GenerateMazeResponse";
  }

  static const char* value(const ::hw1::GenerateMazeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 done\n"
"\n"
;
  }

  static const char* value(const ::hw1::GenerateMazeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateMazeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::GenerateMazeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::GenerateMazeResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_GENERATEMAZERESPONSE_H
