// Generated by gencpp from file hw1/GetGoalState.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GETGOALSTATE_H
#define HW1_MESSAGE_GETGOALSTATE_H

#include <ros/service_traits.h>


#include <hw1/GetGoalStateRequest.h>
#include <hw1/GetGoalStateResponse.h>


namespace hw1
{

struct GetGoalState
{

typedef GetGoalStateRequest Request;
typedef GetGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalState
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::GetGoalState > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::hw1::GetGoalState&) { return value(); }
};

template<>
struct DataType< ::hw1::GetGoalState > {
  static const char* value()
  {
    return "hw1/GetGoalState";
  }

  static const char* value(const ::hw1::GetGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::GetGoalStateRequest> should match
// service_traits::MD5Sum< ::hw1::GetGoalState >
template<>
struct MD5Sum< ::hw1::GetGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetGoalState >::value();
  }
  static const char* value(const ::hw1::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetGoalStateRequest> should match
// service_traits::DataType< ::hw1::GetGoalState >
template<>
struct DataType< ::hw1::GetGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::GetGoalState >::value();
  }
  static const char* value(const ::hw1::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::GetGoalStateResponse> should match
// service_traits::MD5Sum< ::hw1::GetGoalState >
template<>
struct MD5Sum< ::hw1::GetGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetGoalState >::value();
  }
  static const char* value(const ::hw1::GetGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetGoalStateResponse> should match
// service_traits::DataType< ::hw1::GetGoalState >
template<>
struct DataType< ::hw1::GetGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::GetGoalState >::value();
  }
  static const char* value(const ::hw1::GetGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_GETGOALSTATE_H
