// Generated by gencpp from file hw1/GetInitialStateRequest.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GETINITIALSTATEREQUEST_H
#define HW1_MESSAGE_GETINITIALSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct GetInitialStateRequest_
{
  typedef GetInitialStateRequest_<ContainerAllocator> Type;

  GetInitialStateRequest_()
    {
    }
  GetInitialStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::hw1::GetInitialStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::GetInitialStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInitialStateRequest_

typedef ::hw1::GetInitialStateRequest_<std::allocator<void> > GetInitialStateRequest;

typedef boost::shared_ptr< ::hw1::GetInitialStateRequest > GetInitialStateRequestPtr;
typedef boost::shared_ptr< ::hw1::GetInitialStateRequest const> GetInitialStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::GetInitialStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::GetInitialStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::GetInitialStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::GetInitialStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::GetInitialStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::hw1::GetInitialStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/GetInitialStateRequest";
  }

  static const char* value(const ::hw1::GetInitialStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::hw1::GetInitialStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInitialStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::GetInitialStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::hw1::GetInitialStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_GETINITIALSTATEREQUEST_H
