// Generated by gencpp from file hw1/GetInitialState.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GETINITIALSTATE_H
#define HW1_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <hw1/GetInitialStateRequest.h>
#include <hw1/GetInitialStateResponse.h>


namespace hw1
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::GetInitialState > {
  static const char* value()
  {
    return "3601ae784a1cdef6da6662412292fe03";
  }

  static const char* value(const ::hw1::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::hw1::GetInitialState > {
  static const char* value()
  {
    return "hw1/GetInitialState";
  }

  static const char* value(const ::hw1::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::GetInitialStateRequest> should match
// service_traits::MD5Sum< ::hw1::GetInitialState >
template<>
struct MD5Sum< ::hw1::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetInitialState >::value();
  }
  static const char* value(const ::hw1::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetInitialStateRequest> should match
// service_traits::DataType< ::hw1::GetInitialState >
template<>
struct DataType< ::hw1::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::GetInitialState >::value();
  }
  static const char* value(const ::hw1::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::GetInitialStateResponse> should match
// service_traits::MD5Sum< ::hw1::GetInitialState >
template<>
struct MD5Sum< ::hw1::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetInitialState >::value();
  }
  static const char* value(const ::hw1::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetInitialStateResponse> should match
// service_traits::DataType< ::hw1::GetInitialState >
template<>
struct DataType< ::hw1::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::GetInitialState >::value();
  }
  static const char* value(const ::hw1::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_GETINITIALSTATE_H
