// Generated by gencpp from file hw1/GetSuccessor.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_GETSUCCESSOR_H
#define HW1_MESSAGE_GETSUCCESSOR_H

#include <ros/service_traits.h>


#include <hw1/GetSuccessorRequest.h>
#include <hw1/GetSuccessorResponse.h>


namespace hw1
{

struct GetSuccessor
{

typedef GetSuccessorRequest Request;
typedef GetSuccessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSuccessor
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::GetSuccessor > {
  static const char* value()
  {
    return "56c94847518b0fe4a51bc026c1190594";
  }

  static const char* value(const ::hw1::GetSuccessor&) { return value(); }
};

template<>
struct DataType< ::hw1::GetSuccessor > {
  static const char* value()
  {
    return "hw1/GetSuccessor";
  }

  static const char* value(const ::hw1::GetSuccessor&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::GetSuccessorRequest> should match
// service_traits::MD5Sum< ::hw1::GetSuccessor >
template<>
struct MD5Sum< ::hw1::GetSuccessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetSuccessor >::value();
  }
  static const char* value(const ::hw1::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetSuccessorRequest> should match
// service_traits::DataType< ::hw1::GetSuccessor >
template<>
struct DataType< ::hw1::GetSuccessorRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::GetSuccessor >::value();
  }
  static const char* value(const ::hw1::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::GetSuccessorResponse> should match
// service_traits::MD5Sum< ::hw1::GetSuccessor >
template<>
struct MD5Sum< ::hw1::GetSuccessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::GetSuccessor >::value();
  }
  static const char* value(const ::hw1::GetSuccessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::GetSuccessorResponse> should match
// service_traits::DataType< ::hw1::GetSuccessor >
template<>
struct DataType< ::hw1::GetSuccessorResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::GetSuccessor >::value();
  }
  static const char* value(const ::hw1::GetSuccessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_GETSUCCESSOR_H
