// Generated by gencpp from file hw1/IsGoalStateRequest.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_ISGOALSTATEREQUEST_H
#define HW1_MESSAGE_ISGOALSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct IsGoalStateRequest_
{
  typedef IsGoalStateRequest_<ContainerAllocator> Type;

  IsGoalStateRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  IsGoalStateRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::hw1::IsGoalStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::IsGoalStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsGoalStateRequest_

typedef ::hw1::IsGoalStateRequest_<std::allocator<void> > IsGoalStateRequest;

typedef boost::shared_ptr< ::hw1::IsGoalStateRequest > IsGoalStateRequestPtr;
typedef boost::shared_ptr< ::hw1::IsGoalStateRequest const> IsGoalStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::IsGoalStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::IsGoalStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::IsGoalStateRequest_<ContainerAllocator1> & lhs, const ::hw1::IsGoalStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::IsGoalStateRequest_<ContainerAllocator1> & lhs, const ::hw1::IsGoalStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::IsGoalStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::IsGoalStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::IsGoalStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::hw1::IsGoalStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/IsGoalStateRequest";
  }

  static const char* value(const ::hw1::IsGoalStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::hw1::IsGoalStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsGoalStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::IsGoalStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::IsGoalStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_ISGOALSTATEREQUEST_H
