// Generated by gencpp from file hw1/IsGoalStateResponse.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_ISGOALSTATERESPONSE_H
#define HW1_MESSAGE_ISGOALSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct IsGoalStateResponse_
{
  typedef IsGoalStateResponse_<ContainerAllocator> Type;

  IsGoalStateResponse_()
    : is_goal(0.0)  {
    }
  IsGoalStateResponse_(const ContainerAllocator& _alloc)
    : is_goal(0.0)  {
  (void)_alloc;
    }



   typedef double _is_goal_type;
  _is_goal_type is_goal;





  typedef boost::shared_ptr< ::hw1::IsGoalStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::IsGoalStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsGoalStateResponse_

typedef ::hw1::IsGoalStateResponse_<std::allocator<void> > IsGoalStateResponse;

typedef boost::shared_ptr< ::hw1::IsGoalStateResponse > IsGoalStateResponsePtr;
typedef boost::shared_ptr< ::hw1::IsGoalStateResponse const> IsGoalStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::IsGoalStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::IsGoalStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::IsGoalStateResponse_<ContainerAllocator1> & lhs, const ::hw1::IsGoalStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_goal == rhs.is_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::IsGoalStateResponse_<ContainerAllocator1> & lhs, const ::hw1::IsGoalStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::IsGoalStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::IsGoalStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::IsGoalStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9963d9876be49998cdca0abef618060";
  }

  static const char* value(const ::hw1::IsGoalStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9963d9876be4999ULL;
  static const uint64_t static_value2 = 0x8cdca0abef618060ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/IsGoalStateResponse";
  }

  static const char* value(const ::hw1::IsGoalStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 is_goal\n"
"\n"
;
  }

  static const char* value(const ::hw1::IsGoalStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsGoalStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::IsGoalStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::IsGoalStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_goal: ";
    Printer<double>::stream(s, indent + "  ", v.is_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_ISGOALSTATERESPONSE_H
