// Generated by gencpp from file hw1/IsGoalState.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_ISGOALSTATE_H
#define HW1_MESSAGE_ISGOALSTATE_H

#include <ros/service_traits.h>


#include <hw1/IsGoalStateRequest.h>
#include <hw1/IsGoalStateResponse.h>


namespace hw1
{

struct IsGoalState
{

typedef IsGoalStateRequest Request;
typedef IsGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsGoalState
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::IsGoalState > {
  static const char* value()
  {
    return "b368a2d5da7c88f49d77eafba906c151";
  }

  static const char* value(const ::hw1::IsGoalState&) { return value(); }
};

template<>
struct DataType< ::hw1::IsGoalState > {
  static const char* value()
  {
    return "hw1/IsGoalState";
  }

  static const char* value(const ::hw1::IsGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::IsGoalStateRequest> should match
// service_traits::MD5Sum< ::hw1::IsGoalState >
template<>
struct MD5Sum< ::hw1::IsGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::IsGoalState >::value();
  }
  static const char* value(const ::hw1::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::IsGoalStateRequest> should match
// service_traits::DataType< ::hw1::IsGoalState >
template<>
struct DataType< ::hw1::IsGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::IsGoalState >::value();
  }
  static const char* value(const ::hw1::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::IsGoalStateResponse> should match
// service_traits::MD5Sum< ::hw1::IsGoalState >
template<>
struct MD5Sum< ::hw1::IsGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::IsGoalState >::value();
  }
  static const char* value(const ::hw1::IsGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::IsGoalStateResponse> should match
// service_traits::DataType< ::hw1::IsGoalState >
template<>
struct DataType< ::hw1::IsGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::IsGoalState >::value();
  }
  static const char* value(const ::hw1::IsGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_ISGOALSTATE_H
